### ISSUE TITLE
Dubious use of `xmlCleanupParser` and other libxml2 functions

### ISSUE THREAD

**Issue by nwellnhof** [RusXMMS/librcc#1]
I don't think it's a good idea to call `xmlCleanupParser` in `rccXmlFree`. This function is only meant to be called at program exit, for example when checking for memory leaks. Newer libxml2 version will call this function automatically if the library is unloaded.

In addition, `xmlInitCharEncodingHandlers` and `xmlCleanupCharEncodingHandlers` are deprecated and useless. It's enough to call `xmlInitParser` at startup. These functions will be removed in future versions of libxml2.

*I apologize if this is not the official librcc repository. In this case, do you know where I could find the current maintainers?*

**Comment by csa7fff** [comment]
Thanks. I am the maintainer. I will make the changes once I have a bit of free time.

**Comment by csa7fff** [comment]
Fixed by [#c3d3fe7](https://github.com/RusXMMS/librcc/commit/c3d3fe77815578949bd82e54ad6c2ce31bbd88e3)
